---
# handlers file for kubernetes
- name: restart docker
  systemd: 
    name: docker
    state: restarted
- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes