---
- hosts: all
  remote_user: devops
  become: true
  roles:
    - nfs

- hosts: group_master:group_worker
  remote_user: devops
  roles:
    - kubernetes

- hosts: group_master[0]
  remote_user: devops
  roles: 
    - app
